Add S-LoRA
lm-sys/lm-sys.github.io pull request #39
Opened 2023-11-09 20:54 UTC by caoshiyi

2023-11-13 23:28 UTC, merrymercy requested changes

2023-11-13 23:28 UTC, merrymercy commented on blog/2023-11-14-slora.md
> +
Put the result figure `/images/blog/slora/serving_perf.png` here

2023-11-13 23:28 UTC, merrymercy commented on blog/2023-11-14-slora.md
> +<img src="/images/blog/slora/lora_serving_plot_num_adapters.png" style="display:block; margin-top: auto; margin-left: auto; margin-right: auto; margin-bottom: auto; width: 50%"></img>
Simplify this figure:
1. Remove alpha. Readers do not know what is "alpha".
2. Only keep the two curves with alpha = 1.

2023-11-13 23:28 UTC, merrymercy commented on blog/2023-11-14-slora.md
> +| S6      | Llama-70B  | 8192        | {64}            |
The results for other settings are not listed in the blog. Please paste the table from the paper here.

2023-11-13 23:35 UTC, merrymercy requested changes

2023-11-13 23:35 UTC, merrymercy commented on blog/2023-11-14-slora.md
> +### Results
Reorganize this section and try to add more results.

1. Comparison with PEFT and vLLM-packed. (serving_perf.png, Table. 3)
2. Tensor parallelism (Figure. 8)
3. One subfigure from Figure 5.

2023-11-13 23:35 UTC, merrymercy commented on blog/2023-11-14-slora.md
> +
Put `public/images/blog/slora/batch_base_model.png` here, before the experiment results

2023-11-13 23:35 UTC, merrymercy commented on blog/2023-11-14-slora.md
> +
Add the overview figure (Figure. 2) here

2023-11-14 08:56 UTC, Ying1123 approved these changes

2023-11-15 09:37 UTC, merged